### PR TITLE
update syndicated community blog link

### PR DESCRIPTION
**Pull request by zbraiterman**
I've updated the URL, since the previous URL returned a `404:  Page Not Found` error.

### CODE REVIEW

**Comment by vsoch** [comment]
hey @zbraiterman !!! :wave: I'll be able to review this (testing generation) in a few minutes - just need to finish something up!

**Comment by zbraiterman** [comment]
Sounds good to me.  Thanks, @vsoch! :)

**Review by vsoch — APPROVED** [review]
Good catch!

**Comment by zbraiterman** [comment]
Thanks, @vsoch, for the impressively quick response! :)

**Comment by vsoch** [comment]
I didn’t realize it was so quick a fix - I should have glanced at it and merged asap! I’ll do better, faster next time 😆

**Pull request merged**
